#!/bin/bash

##########
#  usage:
#   $ nscp path_to_file dirname
#
#  example:
#   $ nscp /home/foo/bar.jpg  abc_customer123
#

curl -T "$1" -u 'USERNAME:PASSWORD' "ftp://sdjapan.upload.akamai.com/340149/training/$2/" --ftp-create-dirs
BASE=$(basename "$1")
echo "URL: https://docstraining.akamaized.net/$2/$(basename $BASE)"

